sudo: false

os:
- linux

language: node_js

node_js:
- "12"

addons:
  apt:
    packages:
      - libsecret-1-dev

before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
  fi

script:
- yarn
- yarn vscode:prepublish

before_deploy:
- yarn global add vsce;
- vsce package;

deploy:
- provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
    repo: Semyonic/JirAux
    branch: master
    tags: true
    condition: $TRAVIS_OS_NAME = linux
- provider: script
  script: vsce publish -p $VS_TOKEN
  skip_cleanup: true
  on:
    repo: Semyonic/JirAux
    branch: master
    tags: true
    condition: $TRAVIS_OS_NAME = linux
